#!/bin/sh
module=serial_modbus
device=serial_modbus
mode="664"
cd `dirname $0`
set -e
# Group: since distributions do it differently, look for wheel or use staff
if grep -q '^staff:' /etc/group; then
    group="staff"
else
    group="wheel"
fi

if lsmod | grep -q "^$module"; then
    echo "Module $module is loaded."
else
    echo "Module $module is not loaded, loading it."
    if [ -e ${module}.ko ]; then
        echo "Loading local built file ${module}.ko"
        insmod ./$module.ko $* || exit 1
    else
        echo "Local file ${module}.ko not found, attempting to modprobe"
        modprobe ${module} || exit 1
    fi
fi


major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)
rm -f /dev/${device}
mknod /dev/${device} c $major 0
chgrp $group /dev/${device}
chmod $mode  /dev/${device}